version: '3'
networks:
  app-tier:
    name: app-tier

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    networks:
      - app-tier
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes #disable authentification
  kafka:
    image: 'bitnami/kafka:latest'
    depends_on:
      - zookeeper
    networks:
      - app-tier
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    ports:
      - '9092:9092'
      - '9093:9093'
  db:
    image: postgres:15.1 # https://hub.docker.com/_/postgres
    container_name: postgres_poc_ollcargo
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    networks:
      - app-tier  
  spring-api:
    build: . #Automatically run with the Dockerfile in the current directory
    depends_on:
      - db #db must start before API
    networks:
      - app-tier
    ports:
      - 8080:8080
volumes:
  data: {}